server:
  port: 8081  # Port de l'API Gateway

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://angular-frontend:4200"  # Ajout du container Angular
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: reclamation-service
          uri: lb://reclamations-service
          predicates:
            - Path=/reclamations/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - RequestSize=10MB  # Pour éviter les erreurs de taille de requête
            - CircuitBreaker=name=reclamationsCB, fallbackUri=forward:/fallback/reclamations

  # Timeouts pour éviter que les requêtes bloquent
  httpclient:
    connect-timeout: 5000  # 5 secondes pour se connecter
    response-timeout: 10s   # 10 secondes pour recevoir la réponse

logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # ✅ Active les logs détaillés

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: api-gateway  # Change de localhost à api-gateway
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"  # ✅ Active tous les endpoints Actuator
