server:
  port: 8081

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}
  cloud:
    config:
      enabled: true
      fail-fast: false
    gateway:
      discovery:
        locator:
          enabled: true # Enable automatic route creation
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:8081"
              - "http://angular-frontend:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      # Increase timeouts for all routes
      httpclient:
        connect-timeout: 10000 # 10 seconds
        response-timeout: 30s # 30 seconds

# Eureka configuration in case config server is down
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    # Increase cache refresh time
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: api-gateway
    # More frequent health checks
    lease-renewal-interval-in-seconds: 10

# Add debug logging for troubleshooting
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

resilience4j:
  circuitbreaker:
    instances:
      usersCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s  # Increased from 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        # Add timeout configuration
        timeoutDuration: 20s
      commandesCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s  # Increased from 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        # Add timeout configuration
        timeoutDuration: 20s
      reclamationsCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s  # Increased from 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        # Add timeout configuration
        timeoutDuration: 20s
      menuCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s  # Increased from 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        # Add timeout configuration
        timeoutDuration: 20s
      livraisonCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s  # Increased from 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        # Add timeout configuration
        timeoutDuration: 20s
        
  # Add TimeLimiter configuration
  timelimiter:
    instances:
      usersCB:
        timeoutDuration: 20s
        cancelRunningFuture: true
      commandesCB:
        timeoutDuration: 20s
        cancelRunningFuture: true
      reclamationsCB:
        timeoutDuration: 20s
        cancelRunningFuture: true  
      menuCB:
        timeoutDuration: 20s
        cancelRunningFuture: true
      livraisonCB:
        timeoutDuration: 20s
        cancelRunningFuture: true