server:
  port: 8081  # Port de l'API Gateway

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: RECLAMATION-SERVICE
          uri: lb://reclamations-service  # Correspond exactement à `spring.application.name`
          predicates:
            - Path=/reclamations/**
          filters:
            - RewritePath=/reclamations/(?<segment>.*), /$1

eureka:
  client:
    service-url:
      defaultZone: http://192.168.100.3:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"  # ✅ Active tous les endpoints Actuator
